#!/usr/bin/env python

import subprocess
import sys

def check_changes(directory):
    result = subprocess.run(["git", "diff", "--cached", "--name-only", directory], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    
    changed_files = result.stdout.decode("utf-8").splitlines()

    return changed_files

if __name__ == "__main__":
    print("Running pre-commit checks...")

    target_directory = "Assets\\Resources\\Data"

    changed_files = check_changes(target_directory)

    if changed_files:
        print("Changes detected in the following files:")
        for file in changed_files:
            print(f"- {file}")
        sys.exit(0)
    else:
        print("No changes detected. Commit allowed.")
        sys.exit(0)