version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.8

    steps:
      - checkout

      # Установка Unity Hub и сборка WebGL
      - run:
          name: Build Unity Project for WebGL
          command: |
            APPRUN_1="--appimage-extract-and-run" /opt/Unity/Hub/Editor/2022.3.7f1/Editor/Unity \
              -batchmode \
              -projectPath /path/to/your/project \
              -executeMethod BuildScript.BuildWebGL

workflows:
  version: 2
  build:
    jobs:
      - build
