version: 2.1

jobs:
  build:
    docker:
      - image: unityci/editor:windows-2022.3.7f1-universal-windows-platform-2

    steps:
      - checkout
      - run:
          name: Build Unity Project
          command: unity-editor -batchmode -projectPath /root/project -executeMethod BuildScript.Build

workflows:
  version: 2
  build:
    jobs:
      - build
