version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu-2022.3.7f1-webgl-2.0.0

    steps:
      - checkout

      # Установка зависимостей для Unity (если необходимо)
      # - run:
      #     name: Install Unity Dependencies
      #     command: |
      #       apt-get update
      #       apt-get install -y some_dependency

      # Вывод содержимого рабочей директории (для отладки)
      - run:
          name: List Working Directory
          command: |
            ls -la

      # Сборка Unity WebGL проекта
      - run:
          name: Build Unity Project for WebGL
          command: |
            unity-editor -batchmode -projectPath $(pwd) -executeMethod BuildScript.BuildWebGL

workflows:
  version: 2
  build:
    jobs:
      - build
