version: '2.1'
orbs:
  jira: circleci/jira@2.0
  node: circleci/node@5.1
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm test
          name: Test app
      - jira/notify:
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
workflows:
  build-workflow:
    jobs:
      - build:
          context: JIRA_WEBHOOK
