version: 2.1

orbs:
  unity: game-ci/unity@1.6.0

workflows:
  build-unity-project:
    jobs:
      - unity/create-activation-file:
          editor_version: 2022.3.7f1
      - store_artifacts:
          path: Builds/
