version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.8

    steps:
      - checkout

      # Установка Unity Hub
      - run:
          name: Install Unity Hub
          command: |
            curl -o UnityHub.AppImage https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage
            chmod +x UnityHub.AppImage
            ./UnityHub.AppImage -- --install-location /opt/UnityHub

      # Установка зависимостей Unity
      - run:
          name: Install Unity Dependencies
          command: |
            /opt/UnityHub/UnityHub.AppImage --headless install --version 2022.3.7f1 --module "Standard Assets, WebGL Build Support"

      # Выполнение сборки WebGL проекта
      - run:
          name: Build Unity Project for WebGL
          command: |
            /opt/Unity/Hub/Editor/2022.3.7f1/Editor/Unity \
              -batchmode \
              -projectPath /path/to/your/project \
              -executeMethod BuildScript.BuildWebGL

workflows:
  version: 2
  build:
    jobs:
      - build
